#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import re
import shutil
from pathlib import Path

from setuptools import find_packages, setup


# Remove stale visionary_r1.egg-info directory to avoid https://github.com/pypa/pip/issues/5466
stale_egg_info = Path(__file__).parent / "visionary_r1.egg-info"
if stale_egg_info.exists():
    print(
        (
            "Warning: {} exists.\n\n"
            "If you recently updated visionary-r1, this is expected,\n"
            "but it may prevent visionary-r1 from installing in editable mode.\n\n"
            "This directory is automatically generated by Python's packaging tools.\n"
            "I will remove it now.\n\n"
            "See https://github.com/pypa/pip/issues/5466 for details.\n"
        ).format(stale_egg_info)
    )
    shutil.rmtree(stale_egg_info)


# IMPORTANT: all dependencies should be listed here with their version requirements, if any.
#   * If a dependency is fast-moving (e.g. transformers), pin to the exact version
_deps = [
    # Core ML frameworks
    "torch==2.6.0",
    "transformers>=4.49.0",
    "einops>=0.8.0",
    
    # Model training and inference
    "deepspeed==0.16.5",
    "flash-attn==2.7.4.post1",
    "vllm==0.8.3",
    "peft==0.15.2",
    "trl==0.16.0",
    
    # HuggingFace ecosystem
    "huggingface-hub>=0.30.1",
    "tokenizers>=0.21.1",
    
    # Scientific computing
    "numpy>=1.26.4",
    "pandas>=2.2.3",
    
    # Computer vision
    "opencv-python-headless>=4.11.0.86",
    "torchvision==0.21.0",
    
    # Evaluation
    "evaluate>=0.4.3",
    "math-verify>=0.7.0",
    
    # Monitoring
    "wandb>=0.19.9",
    "loguru>=0.7.3",
]

deps = {b: a for a, b in (re.findall(r"^(([^!=<>~ \[\]]+)(?:\[[^\]]+\])?(?:[!=<>~ ].*)?$)", x)[0] for x in _deps)}


def deps_list(*pkgs):
    return [deps[pkg] for pkg in pkgs]


extras = {}
extras["torch"] = deps_list("torch", "torchvision")
extras["eval"] = deps_list("evaluate", "math-verify")
extras["vision"] = deps_list("opencv-python-headless", "torchvision")
extras["monitoring"] = deps_list("wandb", "loguru")
extras["all"] = list(deps.values())

# core dependencies shared across the whole project - keep this to a bare minimum :)
install_requires = [
    deps["torch"],
    deps["transformers"],
    deps["vllm"],
    deps["einops"],
    deps["deepspeed"],
]

setup(
    name="visionary-r1",
    version="1.0.0.dev0",
    author="Visionary R1 Team",
    author_email="xiajiaer@life.hkbu.edu.hk",
    description="Visionary R1 - Advanced AI Vision and Language Model",
    long_description=open("README.md", "r", encoding="utf-8").read() if Path("README.md").exists() else "Visionary R1 Project",
    long_description_content_type="text/markdown",
    keywords="ai vision language model llm vllm transformers",
    license="Apache-2.0",
    url="https://github.com/maifoundations/Visionary-R1",
    packages=find_packages(),
    zip_safe=False,
    extras_require=extras,
    python_requires=">=3.12",
    install_requires=install_requires,
    classifiers=[
        "Development Status :: 4 - Beta",
        "Intended Audience :: Developers",
        "Intended Audience :: Science/Research",
        "License :: OSI Approved :: Apache Software License",
        "Operating System :: OS Independent",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.12",
        "Topic :: Scientific/Engineering :: Artificial Intelligence",
    ],
)