# Model arguments
model_name_or_path: Qwen/Qwen2.5-VL-3B-Instruct
model_revision: main
torch_dtype: bfloat16

# Data training arguments
dataset_name: MMInstruction/Clevr_CoGenT_TrainA_R1
dataset_configs:
- all
preprocessing_num_workers: 8

# SFT trainer config
bf16: true
do_eval: false
eval_strategy: "no"
gradient_accumulation_steps: 4
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
learning_rate: 2.0e-05
log_level: info
logging_steps: 5
logging_strategy: steps
lr_scheduler_type: cosine
packing: false
max_seq_length: 4096
max_steps: -1
num_train_epochs: 1
output_dir: results/SFT
overwrite_output_dir: true
per_device_train_batch_size: 4
push_to_hub: false
report_to:
- none
save_strategy: "steps"
save_steps: 100
save_total_limit: 1
save_only_model: true

seed: 42
warmup_ratio: 0.1